variables:
  MAVEN_IMAGE: registry.nexus.sprouts.kr/maven:3.8.6-openjdk-11-slim

include:
  - project: "sprouts/library/gitlab-ci"
    ref: 0.0.2
    file:
      - 'template/maven-library/prepare.gitlab-ci.yml'
      - 'template/maven-library/build.gitlab-ci.yml'
      - 'template/maven-library/test.gitlab-ci.yml'
      - 'template/maven-library/quality.gitlab-ci.yml'
      - 'template/maven-library/deploy.gitlab-ci.yml'
      - 'template/maven-library/finish.gitlab-ci.yml'

stages:
  - prepare
  - build
  - test
  - quality
  - deploy
  - finish
